// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTask(arg1:main.TaskInput):Promise<main.Task>;

export function BuildProfile(arg1:main.ProfileInput):Promise<main.ProfileSummary>;

export function CenterWindow():Promise<main.WindowCommandResult>;

export function GetState():Promise<main.InteractionState>;

export function GetTrayStatus():Promise<main.TrayStatus>;

export function Greet(arg1:string):Promise<string>;

export function HideToTray():Promise<main.WindowCommandResult>;

export function QuitApp():Promise<void>;

export function SetWindowSize(arg1:main.WindowSizeInput):Promise<main.WindowCommandResult>;

export function SetWindowTitle(arg1:string):Promise<main.WindowCommandResult>;

export function ShowWindow():Promise<main.WindowCommandResult>;
