// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1) {
  return window['go']['main']['App']['AddTask'](arg1);
}

export function BuildProfile(arg1) {
  return window['go']['main']['App']['BuildProfile'](arg1);
}

export function CenterWindow() {
  return window['go']['main']['App']['CenterWindow']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetTrayStatus() {
  return window['go']['main']['App']['GetTrayStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HideToTray() {
  return window['go']['main']['App']['HideToTray']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function SetWindowSize(arg1) {
  return window['go']['main']['App']['SetWindowSize'](arg1);
}

export function SetWindowTitle(arg1) {
  return window['go']['main']['App']['SetWindowTitle'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}
